import Head from 'next/head'
import { useState } from 'react'
import MainSection from '@/components/MainSection/main'
import Link from 'next/link'


export default function Home() {
  const [isLoading, setIsLoading] = useState(false) 
 
  return (
    <>
      <Head>
        <title>ElonsWebtoon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <MainSection isLoading={isLoading} />
      </main>
    </>
  )
}
